name: Build Flutter APKs & Appbundle
on: 
  pull_request:
    branches: 
        - master
    types: [closed]

jobs:
  # Build APKs
  build_apks:
    if: ${{ github.event.pull_request.merged }}
    name: Build APKs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 12
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '12.x'

      - name: Initialize project version
        id: project_version
        uses: its404/get-flutter-version@v1.0.0

      - name: Install Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'     

      - name: Building APK
        run: flutter build apk --release

      - name: Release the APKs
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.project_version.outputs.version_number }}-${{github.run_number}}-apks
          name: "Built Apks ${{ steps.project_version.outputs.version_number }} Build(${{github.run_number}})"